apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app
  labels:
    app: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
